[workspace]
members = ["pc_code/Algorithms", "pc_code/Simulation","pc_code/Quantization"]
default-members = ["pc_code/Algorithms"]

[profile.release]
opt-level = 3
lto = true

[profile.dev]
opt-level = 3